### ISSUE TITLE
Dockerfile is broken

### ISSUE THREAD

**Issue by averri** [TIBCOSoftware/SpotfireDockerScripts#1]
The Docker file presented in https://github.com/TIBCOSoftware/SpotfireDockerScripts/tree/master/Spotfire7.11/SpotfireServerLinuxDocker

... is broken. The line 19 of that file contains missing files:

```
COPY tss-7.11.3.x86_64.rpm fixservername.sh Spotfire.Dxp.sd[n] tss_simpleconfig.tx[t]  /
```

The line above means that all the files - `tss-7.11.3.x86_64.rpm`, `fixservername.sh`, `Spotfire.Dxp.sd[n]`, `tss_simpleconfig.tx[t]` - should be present in the same directory as the Dockerfile. Where are they!?

**Comment by pmckinnis** [comment]
The Docker scripts do not come with the installation media.  The tss-<version>.rpm file must be downloaded from the TIBCO software download site as part of the Spotfire Server for Linux installation media.  The same is true for the Spotfire.Dxp.sdn file.  It is part of the Spotfire Deployment software download.  The tss_simpleconfig.txt file can be copied from the SpotfireServerConfig directory of the GitHub scripts.  

I will make this more clear in the GitHub readme.  There is an article on the TIBCO Community site that has more details: https://community.tibco.com/wiki/tibco-spotfirer-server-docker-scripts.

Thanks.

**Comment by averri** [comment]
Hi @pmckinnis, thanks for informing that. I understand the reason for that now.
